name: Dev Box Accelerator - Deployment
# Run when commits are pushed to feature/gitHubActions
on:
  workflow_dispatch:
    inputs:
      AZURE_ENV_NAME:
        description: 'Azure environment name'
        required: true
        default: 'demo'
      AZURE_LOCATION:
        description: 'Azure region (e.g., eastus, westus)'
        required: true
        default: 'eastus2'

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read

jobs:

  build-and-deploy-to-azure:    
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ github.event_name == 'workflow_dispatch' && inputs.AZURE_ENV_NAME || 'devexp2' }}
      AZURE_LOCATION: ${{ github.event_name == 'workflow_dispatch' && inputs.AZURE_LOCATION || vars.AZURE_LOCATION }}
    
    steps:
      - name: Update all Packages
        run: |
          sudo apt-get update && \
          sudo apt-get upgrade -y
      
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install azd
        uses: Azure/setup-azd@v2

      - name: Build Accelerator Bicep
        run: |
          az bicep build --file ../infra/main.bicep --outdir ../bicepArtifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bicepArtifacts
          path: ../bicepArtifacts

      - name: Log in with Azure (Federated Credentials)
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh

      - name: Provision Infrastructure and Deploy Accelerator
        run: |
          echo "AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}"
          azd provision --no-prompt
        env:
          KEY_VAULT_SECRET: ${{ secrets.KEY_VAULT_SECRET }}
          SOURCE_CONTROL_PLATFORM: 'github'